### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by krisz2000** [mk-dev-team/mk-world-of-imagination#4]
**Is your feature request related to a problem? Please describe.**
It's a bit frustating to me to play with these controls.

**Describe the solution you'd like**
Make an option menu where we can change the default controls.

**Comment by sleepy-monax** [comment]
Yeah i'm from belgium and my keyboard is AZERTY. We need to be able in the framework to remape key to action.

**Comment by Lioncat2002** [comment]
>  We need to be able in the framework to remape key to action.


So... the framework doesn't have the ability to remap yet right?
