### ISSUE TITLE
Texture bug when screen scaling is at 125%

### ISSUE THREAD

**Issue by felixnoiseux** [mk-dev-team/mk-world-of-imagination#5]
Hello, I just discovered your game. It is incredible, thank you for sharing!
I found a bug.
The display of the texture of my player is faulty.
I send you a screenshot.

Have a good day
![Player](https://user-images.githubusercontent.com/12865882/65903745-fa8c4700-e38a-11e9-8fba-af371ad8dd59.PNG)

**Comment by sleepy-monax** [comment]
Happy to hear  :) There should be a file call test.png in the bin forlder can you send it, so I can check if the texture atlas is right.

**Comment by felixnoiseux** [comment]
The texture atlas is right :) I found the bug :  My screen was at 125%. It needs to be set at 100% 
![Capture2](https://user-images.githubusercontent.com/12865882/65906956-68d40800-e391-11e9-987f-6f7cca75eee3.PNG)

**Comment by sleepy-monax** [comment]
The bug is fixed now you should be able to play the game with screen scaling on ;)
