### ISSUE TITLE
Building on arch linux

### ISSUE THREAD

**Issue by EverWinter23** [mk-dev-team/mk-world-of-imagination#6]
Hey!

Having issues while building the project on arch linux. I'm using vscode + omnisharp + dotnet-core, so I have to manually edit the `csproj` file.

Using `dotnet build` produces the following error:

```
The imported project "/usr/share/dotnet/sdk/3.1.103/MonoGame/v3.0/MonoGame.Content.Builder.targets" was not found.Confirm that the expression in the Import declaration "/usr/share/dotnet/sdk/3.1.103//MonoGame/v3.0/MonoGame
.Content.Builder.targets" is correct, and that the file exists on disk.
```

Which makes sense because you can't install `Monogame` using `sudo apt-get install` method.

Installation for monogame:
```
$ wget http:///www.monogame.net/releases/v3.0.1/monogame-sdk.run
$ chmod +x monogame-sdk.run
$ sudo ./monogame-sdk.run
```

Another thing I've noticed, in Hevadea.Game.csproj, it refers to `MonoGame3.0`, will this work with `MonoGame 3.7.1` as mentioned in the REAMDE.md

```
"$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Common.props"
```

My major issue is referring to my installation of MonoGame. Will specifying the absolute path work?

Thanks. I really want to build it, it seems so well implemented. I'm new to MonoGame, and this project seems the best implementation I've come across yet, especially the way you separate the Framework from the actual game, the way entities are implemented, the tiles as well. I thought I'd play around more with it and it would be a great learning experience, but am stuck on step 0.

Any help would be appreciated. Also why switch to C for next `hevadea`?

Edit: 
This is what `dotnet` templates generate for me to use MonoGame and it works.
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <MonoGameContentReference Include="**\*.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder" Version="3.7.0.4" />
    <PackageReference Include="MonoGame.Framework.DesktopGL.Core" Version="3.7.0.7" />
  </ItemGroup>

</Project>
```

I have verified that MonoGame exists in `usr/lib/mono/MonoGame/v3.0/` with `MonoGame.Common.props` and `Assemblies` as well.

Something is working!!! But I get this error, when running, I'm able to see the loading screen but unable to get past it. Had to change a lot of stuff in `csproj` files. What version of `.NET Framework` does this work on? And which one is the linux equivalent?

```
Info [_SpriteAtlas] [141/151] icon/new from assets/icon/new.png
Info [_SpriteAtlas] [142/151] icon/marker_green from assets/icon/marker_green.png
Info [_SpriteAtlas] [143/151] icon/cross from assets/icon/cross.png
Info [_SpriteAtlas] [144/151] icon/load from assets/icon/load.png
Info [_SpriteAtlas] [145/151] icon/marker_blue from assets/icon/marker_blue.png
Info [_SpriteAtlas] [146/151] icon/marker_playerW from assets/icon/marker_playerW.png
Info [_SpriteAtlas] [147/151] icon/marker_red from assets/icon/marker_red.png
Info [_SpriteAtlas] [148/151] icon/marker_playerE from assets/icon/marker_playerE.png
Info [_SpriteAtlas] [149/151] icon/marker_playerS from assets/icon/marker_playerS.png
Info [_SpriteAtlas] [150/151] icon/marker_playerN from assets/icon/marker_playerN.png
Info [_SpriteAtlas] [151/151] icon/marker_yellow from assets/icon/marker_yellow.png
Info [_SpriteAtlas] Sprites Layout from:assets/ done in 318ms
System.InvalidOperationException: This image format is not supported
 ---> System.InvalidOperationException: unknown image type
   at MonoGame.Utilities.ImageReader.Read(Stream stream, Int32& x, Int32& y, Int32& comp, Int32 req_comp)
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Hevadea.Framework.Extension.MonoGameExtension.GetTexture2DFromBitmap(GraphicsDevice device, Bitmap bitmap) in /home/frost/Documents/r2d2/hevadea-monogame/solution/Hevadea.Framework/Extension/MonoGameExtension.cs:line 58
   at Hevadea.Framework.Graphic._SpriteAtlas..ctor(Int32 width, Int32 height, String path) in /home/frost/Documents/r2d2/hevadea-monogame/solution/Hevadea.Framework/Graphic/_SpriteAtlas.cs:line 51
   at Hevadea.Resources.Load() in /home/frost/Documents/r2d2/hevadea-monogame/solution/Hevadea.Game/Resources.cs:line 72
   at Hevadea.Game.Initialize() in /home/frost/Documents/r2d2/hevadea-monogame/solution/Hevadea.Game/Game.cs:line 35
   at Hevadea.Scenes.SceneLoadingScreen.<Load>b__5_0() in /home/frost/Documents/r2d2/hevadea-monogame/solution/Hevadea.Game/Scenes/SceneLoadingScreen.cs:line 28
Info [GraphicManager] Reseting render targets... (450/464)
Info [GraphicManager] Generating fullscreen render target id:0 450/464
Info [GraphicManager] Generating fullscreen render target id:1 450/464
Info [GraphicManager] Generating fullscreen render target id:2 450/464
Info [GraphicManager] Generating fullscreen render target id:3 450/464
Info [Scene] RefreshLayout call!
Info [MonoGameHandler] UnloadContent...
```

Have it working!!!!

Edit:
Seeing this, also can't use stairs. The problem is with `Bitmap` I think, because that is where the build failed last time. And I added the following line to get past that:
```C#
System.IO.MemoryStream memoryStream =
    new System.IO.MemoryStream(bufferSize);
bitmap.Save(memoryStream, System.Drawing.Imaging.ImageFormat.Png);

// EXCEPTION -->
Logger.Log("Bitmap problems!");

memoryStream.Position = 0;
Texture2D texture = Texture2D.FromStream(Rise.MonoGame.GraphicsDevice, memoryStream);

return texture;
```

![bitmap](https://user-images.githubusercontent.com/21227016/81161237-e5bf0400-8fa8-11ea-97be-365f213021dd.png)

**Comment by sleepy-monax** [comment]
Hi @EverWinter23,
This project was originally built using Mono, MonoDevelop and monogame.
The C rewrite was just me playing around with C and Raylib ;)
Also, can you create a pull request with the fixes for dotnet core so we can work on fixing theses issues you get :)

**Comment by EverWinter23** [comment]
I'd love that! Although I just hacked my way through it to make it work, removed large portions of  content in `csproj` files.

I will definitely submit PRs for issues that I did come across apart from that. How do you use the in game debugger?

Thank you.

**Comment by sleepy-monax** [comment]
The F1, F2,.. keys toggle multiple debugging features
